apiVersion: v1
kind: Secret
metadata:
  name: todo-app
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: todo-test
  name: todo-app
  url: https://github.com/saloyiana/devops-tasks