apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
  name: {{ .Values.secret.name }}